server:
  port: 8080

spring:
  mvc:
    pathmatch:
      # Spring Boot 2.6.X使用的路径匹配是PathPatternMatcher
      # swagger3.0开始底层Springfox使用的路径匹配是基于AntPathMatcher
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/hcy?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  servlet:
    multipart:
      max-request-size: 100MB # 最大请求文件大小,默认10MB
      max-file-size: 10MB # 单个请求文件大小,默认1MB

mybatis:
  type-aliases-package: org.example.entity
  configuration:
    # 开启驼峰命名规则映射  表 user_name  -> 实体类 userName
    map-underscore-to-camel-case: true
    # 控制台打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




